# -*- coding: utf-8 -*-
"""Copy of exp. 4 and 5.py*

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kurFFpzIKSuORgn6aUrcpQtVnmq-8umq
"""

#loops
a=1
while a<=100 :
  print(a)
  a+=1

a=50
while a>=1 :
 print(a)
 a-=1

#forloop

for a in range(100,50,-1):
  print(a)

#function
x=min(12,18,29,35,60,65)
y=max(12,18,29,35,60,65)

print(x)
print(y)

x=abs(-5.23)
print(x)

z=pow(4,2)
print(z)

import math
x=math.sqrt(25)
print(x)

x=math.pi
print(x)

m=math.ceil(6.45)
s=math.floor(6.45)

print(m)
print(s)

a=int(input("enter the value of  the a="))

print("the value enter by the nale sir is =",a)
